### PR TITLE
Fix cairo 1.18.0 mac crash, upgrade certifi, always use our libs when zip-installed

### PR DESCRIPTION
**Pull request by schmave**
https://cmu-cs-academy.atlassian.net/browse/CSA-1052

The following code crashes on Mac when run with:
* brew-installed cairo 1.18.0
* pygame==2.5.2 (and others)
* pycairo==1.25.0 (and others)

```python
import cairo
fontCtx = cairo.Context(cairo.ImageSurface(cairo.FORMAT_ARGB32, 0, 0))
fontCtx.text_extents('Hello, world!')

import pygame
pygame.init()
```

### CODE REVIEW

**Comment by schmave** [comment]
test_image_gen is failing for pip-based installs on Mac because the inspector labels aren't bold, nor is the "Exception! App stopped!" error.

Screen Shot 2023-10-20 at 2 34 38 PM


Screen Shot 2023-10-20 at 2 34 27 PM

**Comment by schmave** [comment]
The inspector looks right to me when I run it outside of test_image_gen, and this is a big improvement over the current state of affairs where labels are unusable when using cairo 1.18. But maybe we should see what's going wrong with the tests too.

**Review by austin-schick — COMMENTED** [review]
The code change looks good to me. I think slightly slower startup with `getTextInput` is worth the tradeoff here.

I also think the tests are worth looking into.

Do you have any idea why you can't init pygame after creating text with cairo? And do you think we should report this to the cairo people or pygame people? Maybe even the SDL people.

**Comment by schmave** [comment]
Reported to pygame here: https://github.com/pygame/pygame/issues/4060

**Comment by schmave** [comment]
Ready for one more look @austin-schick

**Comment by schmave** [comment]
Cairo isn't letting us draw bold/italic text on Mac, so that's why the CI build is still failing. https://github.com/pygobject/pycairo/issues/351

**Pull request merged**
