### PR TITLE
Revert "Fix bug in App class's handleKeyRelease method"

### PR DESCRIPTION
**Pull request by austin-schick**
Reverts cmu-cs-academy/desktop-cmu-graphics#95

### CODE REVIEW

**Comment by schmave** [comment]
Does desktop CMU Graphics need a deploy?

**Comment by austin-schick** [comment]
> Does desktop CMU Graphics need a deploy?

Yup! It will after this merge.

**Review by schmave — APPROVED** [review]

**Comment by schmave** [comment]
D'oh! I didn't realize that you hadn't already merged it :)

**Comment by schmave** [comment]
Deploying now after incrementing the version number in a separate change

**Pull request merged**
