### PR TITLE
Fix errors when displaying the inspector

### PR DESCRIPTION
**Pull request by austin-schick**
We don't usually display the inspector when running a desktop program. It only appears when you hold the ctrl key or pause the app. I'm not sure how long this was broken, but displaying the inspector at all currently causes the app to crash.

### CODE REVIEW

**Comment by schmave** [comment]
Oh no! I forgot that we had an inspector in desktop graphics. Can we add a test for this?

**Review by schmave — APPROVED** [review]

**Comment by austin-schick** [comment]
Yeah, what's a good inspector test? Maybe a slightly-hacky addition to test-image-gen?

**Comment by schmave** [comment]
That sounds reasonable. Just something that will cause it to display info about at least one point on the screen. I guess a test where every different type of shape is on the screen is probably the best. But any old thing to make sure it's not completely broken would be a nice improvement.

**Comment by austin-schick** [comment]
Sounds good! I'll open a separate PR with a test sometime in the next few days

**Pull request merged**
