### PR TITLE
Bring Desktop Graphics to parity with Web Graphics (8/22)

### PR DESCRIPTION
**Pull request by austin-schick**
A partner PR in the CS Academy repository updates the test_image_gen tests to make them more easily shared with this codebase. This PR streamlines the process of sharing tests and makes some updates so they pass.

- Update tests to match the web af
- Fix errors in typechecking.py
- Fix errors in colors.py
- Fix errors from colors_es.py
- Preserve exact (integral) Line endpoint values when possible
- Fix some gradient i18n
- Tweak 'images' tests
- Add a script for updating the test_image_gen tests from the cs-academy repository

### CODE REVIEW

**Review by schmave — COMMENTED** [review]
Nice! I think the only thing left here is possible the integer rotation thing that I mentioned in the other PR.

**Comment by austin-schick** [comment]
What do you think about [c2c959e](https://github.com/cmu-cs-academy/desktop-cmu-graphics/pull/31/commits/c2c959e75c0b77f271ea470f3c833df21d987f59)? Is there any reason not to convert all the `5.0`s into `5`s? That seems to be Javascript's behavior.

**Comment by dkosbie** [comment]
Not sure if this question was directed towards me, but I'll answer it....

> What do you think about c2c959e
<https://github.com/cmu-cs-academy/desktop-cmu-graphics/pull/31/commits/c2c959e75c0b77f271ea470f3c833df21d987f59>?
Is there any reason not to convert all the 5.0s into 5s? That seems to be
Javascript's behavior.

I think it may have some surprising behaviors.  I wonder if we should check
if it is within some tiny epsilon of an int and then make it an int.  For
example:
    y1 = (0.1 + 0.2) * 1000 - 100 # 200.00000000000006
    Label('hello', 200, y1) # 'hello' at (200, 200.00000000000006)

And this one:
    y2 = 60 / (0.1 + 0.2) # 199.99999999999997
    Label('hello', 200, y2) # 'hello' at (200, 199.99999999999997)

So something like this:

def intifyNearInts(n, epsilon=10**-10):
    n, sign = abs(n), -1 if (n < 0) else +1
    i = round(n)
    if (abs(n - i) < epsilon): n = i
    return sign*n

def testIntifyNearInts():
    print('Testing intifyNearInts()...', end='')
    assert(intifyNearInts( 200.00000000000006) ==  200)
    assert(intifyNearInts(-200.00000000000006) == -200)
    assert(type(intifyNearInts(200.00000000000006)) == int)
    assert(intifyNearInts( 200.0000000006) ==  200.0000000006)
    assert(intifyNearInts(-200.0000000006) == -200.0000000006)
    assert(intifyNearInts( 399.99999999999997) ==  400)
    assert(intifyNearInts(-399.99999999999997) == -400)
    assert(type(intifyNearInts(399.99999999999997)) == int)
    assert(intifyNearInts( 399.9999999997) ==  399.9999999997)
    assert(intifyNearInts(-399.9999999997) == -399.9999999997)
    print('Passed')

testIntifyNearInts()

Thoughts?

David

**Comment by dkosbie** [comment]
I should add that somehow the formatting of my response was obliterated.
<sigh>

**Comment by austin-schick** [comment]
I didn't realize you were getting Desktop CMU Graphics PR notifications, Koz! I meant to ask Evan, but I'm happy to have your input.

https://github.com/cmu-cs-academy/desktop-cmu-graphics/pull/31/commits/c2c959e75c0b77f271ea470f3c833df21d987f59 is the commit where I made the change to intify shape properties.

My change uses a function similar to `intifyNearInts`:

```python3
def truncateIntegerFloats(n):
    if isinstance(n, float) and n.is_integer():
        return int(n)
    return n
```

I'm trying to capture this behavior of the web animation framework:

```python3
l = Label('hello', 200, (200 / 2))
assert l.centerY == 100 and isinstance(l.centerY, int)
```

without doing more aggressive rounding than it does. This code runs without errors on the site, for example:

```python3
y1 = (0.1 + 0.2) * 1000 - 100
l = Label('hello', 200, y1)
assert l.centerY == 200.00000000000006 and isinstance(l.centerY, float)
```

**Comment by schmave** [comment]
Austin and I talked about this yesterday and we're going to stick with his
change of using truncateIntegerFloats, because it most closely matches what
is happening in the browser (because of the interaction between JS and
Brython). Switching both to doing rounding a la your intifyNearInts would
probably be a nice thing to do sometime in the future.

Evan

**Comment by dkosbie** [comment]
Okey doke.  🙂

**Pull request merged**
