### PR TITLE
Make cmu_graphics pip installable

### PR DESCRIPTION
**Pull request by tate1650**
Text-wise, this is the bulk of the changes that need to be added for the pip installation to work. There are some small changes that may need to be made inside of the cmu_graphics/ directory, too, but I believe these are all the new files that need to be added.

### CODE REVIEW

**Comment by tate1650** [comment]
Okay, so I have now mostly finished up with this pull request. So far, I have

- Set up the config files for uploading to PyPI
- Added and edited the `README` (with a few more small adjustments still to come based off of the comments in the Google Doc)
- Formatted the `.py` files with comment flags that allow you to distinguish between the zip file version and pip version
- Updated the `release.sh` script to do more or less the same thing with the zip file version, but now it also creates a temporary directory for the PyPI upload as well, and when run inside of AppVeyor, it will upload to PyPI

There are still a few things I need to do though.
- [] I need to test this on AppVeyor, as well. As far as I can see, it looks like only the `master` branch has builds run for it on AppVeyor, but I also see there appears to be a way to run builds for other branches. So I could either have this branch merged onto master and test them there, or I could change the AppVeyor settings and run them on this branch. Do you all have a preference for which one I do?
- (Also, it looks like there was a test that failed on the most recent version of `master`. Just wanted to make sure you all were aware)
- [] I will probably need to make a new PyPI token for this repo specifically and figure out a way to add a `.pypirc` file to it such that it will automatically authenticate inside of AppVeyor whenever we deploy the package
- [] I may need to move the PyPI upload code from `release.sh` to a different script, as I think this script just runs after testing and not at deployment. And we wouldn't want to prematurely upload to PyPI, before we send the zipped version to S3. Do you all happen to know what script is run when we deploy the zipped version of the graphics package and where I can find it?
- [] I may or may not need to figure out how to automatically update the version of the package in `setup.py` and `version.txt` every time we make an update, depending on whether it is worth it to do so. I know sometimes we may update the minor or the patch version, so we could either update the two files manually, or we could run a script that takes in a argument indicating whether we are updating the major (probably wouldn't be applicable for a long time), minor, or patch version. What do you all think would be the best option?
- [] I may or may not need to remove the venv from my current version of the repo depending on whether it will actually be needed to run the build. Do you all know if AppVeyor has a built-in version of Python? Or more specifically, where I can find that version and its module directory?
- [] I need to make a couple more small updates to the README
- [] I still need to change the name of the module to cmu-graphics, but I intend to do that as the very last thing

**Comment by tate1650** [comment]
There we go. That should be more readable now. I'll take a closer look into some of your other suggestions later, but I figured I would take care of that first so you can look over the changes.

**Comment by schmave** [comment]
Looking good! Austin knows more about this stuff than I do, so I think he should field your questions. I would just say don't be afraid to rewrite `build/release.sh` in Python now that it is more complicated :)

**Comment by tate1650** [comment]
Just so we have a record of it here, here's a copy of the list of things that still need to be done before Desktop CMU Graphics is fully `pip`-ready (this is the same one that I sent to you all on Slack):

- [ ] Re-enable zip version tests in `tox.ini`
- [ ] Re-enable Windows tests
- [ ] Remove autoupdate for the zip version of the package and remove `test_autoupdate.py` (maybe?)
- [ ] Figure out why samples aren't copied to `pypi_upload` directory
- [ ] Double check that both versions of the package contain all the expected files
- [ ] Maybe remove PYPI env vars from `.appveyor.yml` (they're not used at the moment I don't think; the TestPYPI token is in the PyPI Push Environment settings)
- [ ] Maybe delete `pypi-push.sh` at some point
- [ ] Re-enable automatic version number updating in `release.py`
- [ ] Maybe delete call to `rm_temp_dirs` (currently commented out) in `release.py`
- [ ] Move the PyPI push code from AppVeyor agent script to CodeBuild
    - Are we also doing the S3 push on CodeBuild now, too?
- [ ] Update readme to include MacOS specific instructions
- [ ] Complete final review of readme
- [ ] Reset default AppVeyor branch to `master` when we're finished
- [ ] Enable "Deploy on tag" for AppVeyor
- [ ] Reach out to Replit when package is ready
- [ ] Update `.gitignore` if needed
- [ ] Maybe remove PyPI push environment when CodeBuild is set up?
- [ ] Change PyPI deployment to be regular PyPI at the end
- [ ] Change package name to `cmu_scotty_graphics` at the end (right?)
- [ ] (Not mentioned on Slack) resolve merge conflicts with `master`

**Pull request closed without merging**
